### ISSUE TITLE
Tutorial interativo

### ISSUE THREAD

**Issue by guilacerda** [Escola-em-Casa/android-escola-em-casa#30]
**Descrição da nova feature:**

Muitos usuários estão com dúvidas de como utilizar o aplicativo. A ideia é que ao entrar pela primeira vez no aplicativo, o usuário seja redirecionado para o tutorial que o ensinará como utilizar o app (quais telas existem, como interagir com cada tela, etc).

Idealmente o tutorial guiaria o usuário na navegação das telas. Dando highlight nos botões que ele tem que clicar, etc.

Mas sempre bom debatermos o melhor modo de desenvolver para entregar a funcionalidade o mais rápido possível, tendo em vista que os novos usuários estão chegando agora.

**Tarefas**

- [ ] Criar um botão de tutorial na página Sobre nós
- [ ] Idealizar, nessa issue, qual será o modelo do tutorial
- [ ] Abrir issues para resolução de cada story

**Critérios de aceitação**

- [ ] A ideia tem que ser debatida e aceita pela comunidade

**Comment by markinlimac** [comment]
Para resolução dessa issue pode ser usada alguma lib que implementa o guided tour, como a <a href="https://github.com/amlcurran/ShowcaseView">showcase View</a>? Creio que resolver essa issue from scratch não seja viável, a não ser que o tutorial seja feito de outra maneira, como uma tela que possui um carrossel de imagens que mostra as funcionalidades do app.
